# Generated by Django 3.2.12 on 2022-03-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuefuapp', '0002_alter_groundqueue_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undergroundqueue',
            name='process_status',
            field=models.IntegerField(choices=[(0, '等待中'), (1, '待办理'), (2, '已办理'), (3, '撤销')], default=1, verbose_name='办理情况'),
        ),
    ]
