# Generated by Django 3.2.12 on 2022-03-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuefuapp', '0004_auto_20220321_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundqueue',
            name='complete_date',
            field=models.DateField(blank=True, null=True, verbose_name='完成日期'),
        ),
        migrations.AlterField(
            model_name='undergroundqueue',
            name='complete_date',
            field=models.DateField(blank=True, null=True, verbose_name='完成日期'),
        ),
    ]
