# Generated by Django 3.2.12 on 2022-03-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuefuapp', '0005_auto_20220321_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundqueue',
            name='apply_date',
            field=models.DateField(blank=True, null=True, verbose_name='申请日期'),
        ),
        migrations.AlterField(
            model_name='undergroundqueue',
            name='apply_date',
            field=models.DateField(blank=True, null=True, verbose_name='申请日期'),
        ),
    ]
