# Generated by Django 3.2.12 on 2022-03-22 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xuefuapp', '0006_auto_20220321_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundqueue',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_queue_info', to='xuefuapp.car', verbose_name='地面排队'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='room_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='房间号码'),
        ),
        migrations.AlterField(
            model_name='undergroundqueue',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underground_queue_info', to='xuefuapp.car', verbose_name='地库排队'),
        ),
    ]
