# Generated by Django 3.2.12 on 2022-03-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuefuapp', '0007_auto_20220322_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='approve_status',
            field=models.IntegerField(choices=[(1, '待核实'), (2, '通过'), (3, '不通过'), (4, '资料不全')], default=1, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='car',
            name='card_type',
            field=models.IntegerField(choices=[(1, '地面月卡'), (2, '地面临时'), (3, '地库月卡'), (4, '地库固定'), (5, '其它')], default=5, verbose_name='卡类型'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='approve_status',
            field=models.IntegerField(blank=True, choices=[(1, '待核实'), (2, '通过'), (3, '不通过'), (4, '资料不全')], null=True, verbose_name='确认状态'),
        ),
    ]
