# Generated by Django 3.2.12 on 2022-04-01 15:12

from django.db import migrations, models
import xuefuapp.models
import xuefuapp.storage


class Migration(migrations.Migration):

    dependencies = [
        ('xuefuapp', '0009_auto_20220401_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='doc_zulinchengnuoshu',
        ),
        migrations.RemoveField(
            model_name='car',
            name='doc_zulinxiei',
        ),
        migrations.AddField(
            model_name='car',
            name='doc_chengnuoshu',
            field=models.FileField(blank=True, null=True, storage=xuefuapp.storage.OverwriteStorage(), upload_to=xuefuapp.models.chengnuoshu_path, verbose_name='承诺书页面'),
        ),
        migrations.AddField(
            model_name='car',
            name='doc_zulinhetong',
            field=models.FileField(blank=True, null=True, storage=xuefuapp.storage.OverwriteStorage(), upload_to=xuefuapp.models.zulinhetong_path, verbose_name='租赁合同页面'),
        ),
        migrations.AlterField(
            model_name='car',
            name='approve_status',
            field=models.IntegerField(choices=[(1, '待核验'), (2, '通过'), (3, '不通过'), (5, '资料不全'), (4, '欠费')], default=1, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='approve_status',
            field=models.IntegerField(blank=True, choices=[(1, '待核验'), (2, '通过'), (3, '不通过'), (5, '资料不全'), (4, '欠费')], null=True, verbose_name='确认状态'),
        ),
    ]
