# Generated by Django 3.2.12 on 2022-04-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuefuapp', '0011_car_car_of'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': '车辆', 'verbose_name_plural': '所有车辆'},
        ),
        migrations.AlterField(
            model_name='car',
            name='car_of',
            field=models.IntegerField(choices=[(1, '业主'), (2, '租户')], default=1, verbose_name='业主/租户'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='wx_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='开放ID'),
        ),
    ]
