# Generated by Django 3.2.12 on 2022-05-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuefuapp', '0013_alter_owner_approve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='room_id',
            field=models.CharField(max_length=20, verbose_name='房间号码'),
        ),
    ]
