# Generated by Django 3.2.12 on 2022-06-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuefuapp', '0014_alter_owner_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='内部ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='操作日期')),
                ('created_by', models.CharField(max_length=20, verbose_name='操作人员')),
                ('filename', models.CharField(max_length=100, verbose_name='文件名称')),
                ('filetype', models.CharField(max_length=20, verbose_name='文件类型')),
                ('operation', models.IntegerField(choices=[(0, '导入文件'), (1, '导出文件')], default=0, verbose_name='文件操作')),
            ],
            options={
                'verbose_name': '导入导出文件',
                'verbose_name_plural': '导入导出文件',
            },
        ),
    ]
