# Generated by Django 3.2.12 on 2022-08-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xuefuapp', '0016_undergroundqueue2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundqueue',
            name='process_status',
            field=models.IntegerField(choices=[(0, '等待中'), (1, '待办理'), (2, '已办理'), (3, '撤销')], default=0, verbose_name='办理情况'),
        ),
        migrations.AlterField(
            model_name='undergroundqueue',
            name='process_status',
            field=models.IntegerField(choices=[(0, '等待中'), (1, '待办理'), (2, '已办理'), (3, '撤销')], default=0, verbose_name='办理情况'),
        ),
        migrations.AlterField(
            model_name='undergroundqueue2',
            name='process_status',
            field=models.IntegerField(choices=[(0, '等待中'), (1, '待办理'), (2, '已办理'), (3, '撤销')], default=0, verbose_name='办理情况'),
        ),
    ]
